# Teleop configuration for 8BitDo Pro 2 Gamepad using the D mode configuration.
# 8BitDo Pro2 Axes and Buttons:
# axes[0-7]:
# [0] = left stick +left / -right
# [1] = left stick +up / -down
# [2] = right stick +left / -right
# [3] = right stick +up / -down
# [4] = R2
# [5] = L2
# [6] = Dpad +left / -right
# [7] = Dpad +up / -down

# buttons[0-15]: (0 = not pressed / 1 = pressed)
# [0] = A
# [1] = B
# [2] = ???
# [3] = X
# [4] = Y
# [5] = ???
# [6] = L
# [7] = R
# [8] = ???
# [9] = ???
# [10] = Select
# [11] = Start
# [12] = Turbo (checker board button)
# [13] = left stick button
# [14] = right stick button
# [15] = ???

teleop_twist_joy:
  axis_linear: 1
  scale_linear: 0.4
  scale_linear_turbo: 1.0
  axis_angular: 2
  scale_angular: 0.6
  scale_angular_turbo: 1.2
  enable_button: 6
  enable_turbo_button: 7
joy_node:
  deadzone: 0.1
  autorepeat_rate: 20
  dev: /dev/input/js0